# Regenerates assets/js/search-index.js from the page content.
# Run after editing any page copy:   powershell -File tools\build-search-index.ps1

$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent

$pages = @(
  @{ f = 'index.html';           t = 'Home' },
  @{ f = 'about-us.html';        t = 'About Us' },
  @{ f = 'services.html';        t = 'Services' },
  @{ f = 'resource-center.html'; t = 'Resource Center' },
  @{ f = 'contact-us.html';      t = 'Contact Us' },
  @{ f = 'client-portal.html';   t = 'Client Portal' }
)

# Chrome that appears on every page and would pollute every result snippet.
$noise = @('Skip to main content', 'Search this site', 'Open menu')

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('/* AUTO-GENERATED by tools/build-search-index.ps1 - do not edit by hand. */')
[void]$sb.AppendLine('window.SITE_INDEX = [')

foreach ($p in $pages) {
  $c = [System.IO.File]::ReadAllText((Join-Path $root $p.f))

  foreach ($pat in '(?s)<script.*?</script>', '(?s)<style.*?</style>', '(?s)<!--.*?-->',
                   '(?s)<header.*?</header>', '(?s)<footer.*?</footer>', '(?s)<form.*?</form>') {
    $c = [regex]::Replace($c, $pat, ' ')
  }

  $c = [regex]::Replace($c, '<[^>]+>', ' ')
  $c = [System.Net.WebUtility]::HtmlDecode($c)
  foreach ($n in $noise) { $c = $c.Replace($n, ' ') }
  $c = ($c -replace '\s+', ' ').Trim()

  # drop the leading duplicate of the <title>, which repeats the page name
  if ($c.StartsWith($p.t)) { $c = $c.Substring($p.t.Length).Trim() }

  $c = $c -replace '\\', '\\' -replace '"', '\"'

  [void]$sb.AppendLine("  { title: `"$($p.t)`", url: `"$($p.f)`", modified: `"Jul 19, 2025`", text: `"$c`" },")
}

[void]$sb.AppendLine('];')

$out = Join-Path $root 'assets\js\search-index.js'
[System.IO.File]::WriteAllText($out, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Wrote $out ($((Get-Item $out).Length) bytes)"
